### ISSUE TITLE
Multiple choice: error when page is opening

### ISSUE THREAD

**Issue by tammoterhark** [tammoterhark/ls3-covid-theme#1]
When a multiple choice question needs 1, 2 or 3 answers and the page is opening, 0 answers have been filled in (obviously). The question class is already: .input-error.

Jan was working on something that implement that this class is placed only after any of the subquestions has been filled (and the conditions for error are valid).

**Comment by Jan-E** [comment]
Use input-error-clicked for the error lay-out. That class will only be set after an initial click.

**Comment by Jan-E** [comment]
Clearing all 'input-error' classes at the very end of the document ready function seems to do the trick as well: https://github.com/tammoterhark/ls3-covid-theme/commit/10b726b1ec28f26c4648288105779469c51e7d5c

Then you can stay using the 'input-error' c;lass for the error lay-out.

**Comment by Jan-E** [comment]
@tammoterhark Do you still need custom classes at question level? Or is input-error just enough now

**Comment by tammoterhark** [comment]
Great

**Comment by tammoterhark** [comment]
Not sure if this is the result of your refactoring or my styling of the multiple choice question, but question shows error when page is opened. Can you please take a look?

Furthermore several warnings about JQMIGRATE in console. Doesn't that go wrong somewhere?

**Comment by tammoterhark** [comment]
https://survey.toolsforresearch.com/index.php/632676?newtest=Y&lang=en

**Comment by Jan-E** [comment]
Delaying the removeClass('input-error') with 0 (!) seconds already does the trick. But to be sure I fire another one after .5 seconds delay.

**Comment by Jan-E** [comment]
> Furthermore several warnings about JQMIGRATE in console. Doesn't that go wrong somewhere?

The vanilla theme has the same warnings. I would not bother about it.
