### ISSUE TITLE
Covidlogo

### ISSUE THREAD

**Issue by Jan-E** [tammoterhark/ls3-covid-theme#2]
The logo in the repo does not match the logo that is present in
https://survey.toolsforresearch.com/index.php/614615?newtest=Y&lang=en

There is a covidlogo.png in
/home/admin/domains/survey.toolsforresearch.com/public_html/upload/surveys/632676/images
/home/admin/domains/survey.toolsforresearch.com/public_html/upload/surveys/614615/images

https://survey.toolsforresearch.com/tmp/assets/d9955d08/covidlogo.png

**Comment by Jan-E** [comment]
With a fully up-to-date covid theme from this git repo I am seeing this, when I change the theme to covid:
![Capture](https://user-images.githubusercontent.com/1757825/78088259-e53cb780-73c3-11ea-94fe-d0fbf6ca65c8.PNG)

**Comment by Jan-E** [comment]
One way of solving this is to replace files/logo.png by the Covid logo, but I am not sure if this is the best solution. When I tested this locally on my x out of y survey I ran into a problem om the 'Thank you' page:

![Capture](https://user-images.githubusercontent.com/1757825/78106394-99096b80-73f3-11ea-8646-b814e49dadb7.PNG)

Black test on a dark background ...

**Comment by tammoterhark** [comment]
Stefan added the svg code for the logo directly into the theme files.
