### ISSUE TITLE
Custom.js customisation, one more issue

### ISSUE THREAD

**Issue by tammoterhark** [tammoterhark/ls3-covid-theme#3]
@Jan-E : can you please look into the most recent change? I added view files, because the radio-item class really needs to be set on the li and not on the underlying div. Could you please tweak the custom.js accordingly? Please check if data is being saved in the DB. Thanks!

**Comment by Jan-E** [comment]
Fixed with https://github.com/tammoterhark/ls3-covid-theme/commit/e87498cbda086fc3ee690bad8690b8ec81267884
Please review and close the issue if confirmed
